# Test reject request
# Be sure to add your existing Roles
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::373011342827:user/teste-k8s-training
      username: teste-k8s-training
kind: ConfigMap
metadata:
  name: aws-auth-1
  namespace: kube-system
  labels:
    name: aws-auth
