apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-auth-validator
  namespace: kube-system
  labels:
    app: aws-auth-validator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-auth-validator
  template:
    metadata:
      labels:
        app: aws-auth-validator
    spec:
      # SA corresponds to the SA created by the IRSA setup script.
      serviceAccountName: aws-auth-validator
      containers:
        - name: aws-auth-validator
          image: public.ecr.aws/t4h9q3m4/webhook:latest
          env:

            # Mandatory values. Change these
            - name: CLUSTER_NAME
              value: k8s-brlink-dev
            - name: CLUSTER_REGION
              value: us-east-1

            # Optional parameter. Defaults to None
            # Specify any additional Roles/IAM-users that needs to be present in the aws-auth. This will prevent those roles/users getting locked out intentionally or otherwise.
            # Accept comma-saperated values without spaces. Eg - value: "arn:aws:iam::111122223333:role/AmazonEKSFargatePodExecutionRole,arn:aws:iam::111122223333:user/ops-user"
            - name: ADDITIONAL_ROLES
              #value: "ENTER ARN"

            # Optional parameter. Defaults to None
            # IAM Roles defined via REJECT_ROLES environment variable in the Deployment will not be allowed in the aws-auth. This is particularly useful where a specific user/Role should be denied access and also helps in cases where cluster creator should not be defined in aws-auth as best practice. REJECT_ROLES env variable accepts comma-separated values
            #            - name: REJECT_ROLES
            #              value: ""

            # If TESTING is set to True, webhook will intercept configMaps with any name as long as it has label name=aws-auth and perform validation. This is useful if testing within kube-system namespace but you don't want to test on actual aws-auth configMap  

            # If TESTING is set to False, webhook will intercept configMaps with name aws-auth as long as it has label name=aws-auth and perform validation. Other configMaps that have a different name but have label name=aws-aut will be allowed to pass through without performing any validation

            # Possible values: "True or False"
            # Default value: True
            - name: TESTING
              value: "True"
          imagePullPolicy: Always
          volumeMounts:
            - name: aws-auth-validator-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: aws-auth-validator-certs
          secret:
            secretName: aws-auth-validator-certs
---
apiVersion: v1
kind: Service
metadata:
  name: aws-auth-validator-svc
  namespace: kube-system
  labels:
    app: aws-auth-validator
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: aws-auth-validator           
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: aws-auth-validator
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1akNDQXFLZ0F3SUJBZ0lVSDBFMVFRM0F1UWtUaUUrRlNHM0I1WEJKUDRnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF4TUthM1ZpWlhKdVpYUmxjekFlRncweU1qQTRNall5TWpFMU1EQmFGdzB5TXpBNApNall5TWpFMU1EQmFNREV4THpBdEJnTlZCQU1USm1GM2N5MWhkWFJvTFhaaGJHbGtZWFJ2Y2kxemRtTXVhM1ZpClpTMXplWE4wWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXZCaVUKQ3lxRDhRWmYwMU5OTzZQOUorWlJoeTl3cFZqcTIvbjhWN29xQVhxNXU1NlJZSTJhN1IxRE14YUZjMjVUS3Arego0dURUdFEvT2tZZktxS2dZMTVlTXFUbnN6TS9BbWxqYkFmVjBDelE2dVdtRkxWOEZtN1laT3JqcXREdWgyT211Cm9xSlJSeHJSSVNtZldCenA0MWdWK0pWbkJuTHQ4N3J5MCtsamt0NER2RUwzWTdxZHkvSTN3RDdCeHl4Y0l6dWsKYUgwSWNCVURzcWF0cHFyOU5CV3RRTTZXcEtwOURSbXFKV09Qcmo2czlHT0h4bFE2emJ5VzlnemVHV0oxR0hhaQozSyt4aVlCQVQ4MUtSNkNsVjBTaG02QkREQU43WEU2VThNUCs0SmFNV0FXem5LK25vMHBNZzZtMjgxNGpJQklECmpuS2NKOEhPai84SEk4dHA4UUlEQVFBQm80SGxNSUhpTUE0R0ExVWREd0VCL3dRRUF3SUZvREFUQmdOVkhTVUUKRERBS0JnZ3JCZ0VGQlFjREFUQU1CZ05WSFJNQkFmOEVBakFBTUIwR0ExVWREZ1FXQkJRanRkN25IQjk4Q0RGZwpjcVdiak1vaFNLYm1xakFmQmdOVkhTTUVHREFXZ0JTM2VBN1lsREYxc0E3RVRYRXJGU1hneGFmNk5qQnRCZ05WCkhSRUVaakJrZ2haaGQzTXRZWFYwYUMxMllXeHBaR0YwYjNJdGMzWmpnaUpoZDNNdFlYVjBhQzEyWVd4cFpHRjAKYjNJdGMzWmpMbXQxWW1VdGMzbHpkR1Z0Z2laaGQzTXRZWFYwYUMxMllXeHBaR0YwYjNJdGMzWmpMbXQxWW1VdApjM2x6ZEdWdExuTjJZekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBditUNDdwS0hpazZmWmttVDdYcWtHM0QrCk9pR2kwN2tEbG8xOXh5NEpqR2dEdmpnT05MZ1hxaVdiUFQrU0RKZjVVc1ZHUTlMRVU1YndydXJNMDJzUHVPYlMKVzdsWVVkS3JEVVJaUS9XQ0FQMGNOcTRnUHgwc0lSQVZNVjFib1BEN0lxL1JHWXJFU1JGZFBhWlZPeFFrWVZkYQpseDlCZ1prZTA1V0doc0c4WnpjaGp1Mlhoc0U3dGpQRmp1RzlBVkw5U0dwUXFLMDdtVTFBMFZsRlBNRXRlUC9kClNKMkdCNW9vUHhqbzV0NkV5elNPbFBOZjNwY3pVV1A4UTFyR3ZSemdGSjgyRGkwY0MvWnJVMlZ4VGxQaFZySVoKemNRUC9NWXBpbmFtVER1WXRHanpubEF2Y3B6aTVsMnlPVkdOM1BtZWNRSlZtK3RjWmJETlBGUWlPOEZQY2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: aws-auth-validator-svc
      namespace: kube-system
      path: /validate/configmaps
      port: 443
  failurePolicy: Fail
  matchPolicy: Exact
  # change me. However, will work with the default value
  name: validatingwebhook.test.com
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
      - kube-system
  objectSelector:
    matchLabels:
      name: aws-auth
  rules:
  - apiVersions:
    - '*'
    apiGroups: ["*"]
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources: ["configmaps"]
    scope: Namespaced
  sideEffects: None
  timeoutSeconds: 30
